# Generated by Django 5.1.2 on 2024-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonprogress_unique_student_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
    ]
