# Generated by Django 5.1.2 on 2024-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file_type',
            new_name='file_extension',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='application\\pdf', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
